
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: api-demo-mr-1-cors
plugin: cors
config:
  origins:
    - https://devportal-homolog.apr.vee.codes
    - https://devportal.apr.vee.codes
  credentials: false
  max_age: 3600
  preflight_continue: false
---
apiVersion: v1
kind: Service
metadata:
  name: api-demo-mr-1-service-0
spec:
  externalName: kong.vkpr.platform.vee.codes
  type: ExternalName
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-demo-mr-1
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/strip-path: "true"
    konghq.com/plugins: api-demo-mr-1-cors
spec:
  rules:
    - host: kong.vkpr.platform.vee.codes
      http:
        paths:
          - backend:
              service:
                name: api-demo-mr-1-service-0
                port:
                  number: 80
            path: /api-demo-mr-1/api-spec-agerio/.*
            pathType: ImplementationSpecific
  ingressClassName: kong
